FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir gunicorn
COPY . .
EXPOSE 8000
CMD python -m gunicorn --bind 0.0.0.0:${PORT:-8000} app:app
